import './components/location/location.js';
import './components/body/body.js';
import './components/standart-button/standart-button.js';
import './components/navigation/navigation.js';
import './components/form/form.js';

import './scss/index.scss';

import './components/body/favicon.png';
import './components/home/home.png';
import './components/user-profile/sarah_image.jpg';
import './components/user-profile/john_image.jpg';
import './components/news/news.jpg';
import './components/portfolio/first_project.jpg';
import './components/portfolio/second_project.jpg';
import './components/portfolio/third_project.jpg';
import './components/portfolio/fourth_project.jpg';
import './components/location/marker.png';
import './components/location/pin.png';
import './components/location/target.png';
import './components/news/news.jpg';
import './components/search/search.png';
import './components/events/events.jpg';
import './components/messaging/camera.png';
import './components/messaging/chat.png';
import './components/video-frame/expand.svg';
import './components/video-frame/pause.svg';
import './components/video-frame/play.svg';
import './components/video-frame/video_background.jpg';
